CREATE TABLE IF NOT EXISTS settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  k  VARCHAR(64) UNIQUE NOT NULL,
  v  TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO settings (k, v) VALUES ('welcome', 'Hello from MySQL!')
ON DUPLICATE KEY UPDATE v = VALUES(v);
